apiVersion: v2
name: bucketwise-backend
description: Bucketwise backend service
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mongodb
    version: "0.10.1"
    repository: "oci://registry-1.docker.io/cloudpirates"
    condition: mongodb.enabled
